/**
 * Book Data Loader
 * Provides data for all 66 Bible book overview pages using hardcoded metadata
 * and cross-referencing with priority verses for key verse sections.
 */

import { BookPageData } from '@/components/templates/BookOverviewPage';
import priorityVerses from '@/data/priority-1000.json';

interface PriorityVerse { id: number; book: string; chapter: number; verse: number; slug: string; text_niv: string; }

interface BookMeta {
    name: string; slug: string; testament: string; chapters: number; verses: number;
    author?: string; dateWritten?: string;
    summary: string;
    themes: Array<{ name: string; description: string }>;
}

const BOOKS: BookMeta[] = [
    { name: 'Genesis', slug: 'genesis', testament: 'Old Testament', chapters: 50, verses: 1533, author: 'Moses', dateWritten: '~1445 BC', summary: 'Genesis records the creation of the world, the fall of humanity, the flood, and the beginnings of God\'s covenant people through Abraham, Isaac, Jacob, and Joseph.\n\nIt establishes the foundational narrative of Scripture: God creates, humanity falls, and God begins His plan of redemption through a chosen people.', themes: [{ name: 'Creation', description: 'God creates the heavens, earth, and all life, declaring it good.' }, { name: 'The Fall', description: 'Humanity\'s disobedience introduces sin and death into the world.' }, { name: 'Covenant', description: 'God establishes His covenant promises with Abraham and his descendants.' }, { name: 'Providence', description: 'Through Joseph\'s story, God works through adversity for His purposes.' }] },
    { name: 'Exodus', slug: 'exodus', testament: 'Old Testament', chapters: 40, verses: 1213, author: 'Moses', summary: 'Exodus tells the story of Israel\'s deliverance from slavery in Egypt through God\'s power, the giving of the Law at Mount Sinai, and the construction of the Tabernacle.\n\nIt reveals God as the great Redeemer and Lawgiver who forms a nation for Himself.', themes: [{ name: 'Deliverance', description: 'God rescues His people from slavery through mighty acts.' }, { name: 'The Law', description: 'God gives the Ten Commandments and covenant regulations.' }, { name: 'God\'s Presence', description: 'The Tabernacle symbolizes God dwelling among His people.' }] },
    { name: 'Leviticus', slug: 'leviticus', testament: 'Old Testament', chapters: 27, verses: 859, author: 'Moses', summary: 'Leviticus details the laws of sacrifice, purity, and holiness that set Israel apart as God\'s holy nation. It establishes the priesthood and the Day of Atonement.', themes: [{ name: 'Holiness', description: 'God calls His people to be holy as He is holy.' }, { name: 'Sacrifice', description: 'The sacrificial system points forward to ultimate atonement.' }] },
    { name: 'Numbers', slug: 'numbers', testament: 'Old Testament', chapters: 36, verses: 1288, author: 'Moses', summary: 'Numbers records Israel\'s wilderness wanderings, census counts, and the consequences of disobedience, as well as God\'s faithfulness despite the people\'s rebellion.', themes: [{ name: 'Faithfulness', description: 'God remains faithful despite Israel\'s rebellions.' }, { name: 'Discipline', description: 'Disobedience has consequences, but God\'s mercy endures.' }] },
    { name: 'Deuteronomy', slug: 'deuteronomy', testament: 'Old Testament', chapters: 34, verses: 959, author: 'Moses', summary: 'Deuteronomy contains Moses\' farewell speeches to Israel before entering the Promised Land, restating the Law and urging faithfulness.', themes: [{ name: 'Obedience', description: 'Blessings follow obedience to God\'s commands.' }, { name: 'Remembrance', description: 'Israel is called to remember God\'s mighty acts.' }] },
    { name: 'Joshua', slug: 'joshua', testament: 'Old Testament', chapters: 24, verses: 658, author: 'Joshua', summary: 'Joshua records Israel\'s conquest and division of the Promised Land under Joshua\'s leadership, fulfilling God\'s promise to Abraham.', themes: [{ name: 'Conquest', description: 'God gives victory as Israel follows His commands.' }, { name: 'Inheritance', description: 'Each tribe receives their promised portion of the land.' }] },
    { name: 'Judges', slug: 'judges', testament: 'Old Testament', chapters: 21, verses: 618, summary: 'Judges depicts a cycle of sin, oppression, repentance, and deliverance through God-appointed leaders (judges) in early Israel.', themes: [{ name: 'Cycle of Sin', description: 'Israel repeatedly turns from God and faces consequences.' }, { name: 'Deliverance', description: 'God raises up judges to rescue His people.' }] },
    { name: 'Ruth', slug: 'ruth', testament: 'Old Testament', chapters: 4, verses: 85, summary: 'Ruth tells the story of a Moabite woman\'s faithfulness to her Israelite mother-in-law and her redemption through Boaz. Ruth becomes an ancestor of King David and Jesus Christ.', themes: [{ name: 'Loyalty', description: 'Ruth\'s devotion to Naomi exemplifies faithful love.' }, { name: 'Redemption', description: 'Boaz acts as a kinsman-redeemer, foreshadowing Christ.' }] },
    { name: '1 Samuel', slug: '1-samuel', testament: 'Old Testament', chapters: 31, verses: 810, summary: 'First Samuel traces the transition from the judges to the monarchy, featuring the prophet Samuel, King Saul\'s rise and fall, and David\'s anointing.', themes: [{ name: 'Kingship', description: 'Israel demands a king, revealing the tension between human and divine rule.' }, { name: 'God\'s Sovereignty', description: 'God chooses David, a man after His own heart.' }] },
    { name: '2 Samuel', slug: '2-samuel', testament: 'Old Testament', chapters: 24, verses: 695, summary: 'Second Samuel records David\'s reign as king, his victories, his sin with Bathsheba, and the consequences that follow within his family.', themes: [{ name: 'Grace', description: 'God extends grace despite David\'s failures.' }, { name: 'Consequences', description: 'Sin brings painful consequences even when forgiven.' }] },
    { name: '1 Kings', slug: '1-kings', testament: 'Old Testament', chapters: 22, verses: 816, summary: 'First Kings covers Solomon\'s glorious reign, the building of the Temple, the kingdom\'s division, and the ministry of Elijah.', themes: [{ name: 'Wisdom', description: 'Solomon\'s wisdom and eventual downfall through idolatry.' }, { name: 'Division', description: 'The kingdom splits due to unfaithfulness.' }] },
    { name: '2 Kings', slug: '2-kings', testament: 'Old Testament', chapters: 25, verses: 719, summary: 'Second Kings continues the history of the divided kingdoms through their conquests, featuring the prophets Elijah and Elisha.', themes: [{ name: 'Judgment', description: 'Both kingdoms fall due to persistent idolatry.' }, { name: 'Prophecy', description: 'God sends prophets to warn and guide His people.' }] },
    { name: '1 Chronicles', slug: '1-chronicles', testament: 'Old Testament', chapters: 29, verses: 942, summary: 'First Chronicles retells the history of Israel from Adam to David, emphasizing the Davidic covenant and worship.', themes: [{ name: 'Worship', description: 'David organizes worship and prepares for the Temple.' }] },
    { name: '2 Chronicles', slug: '2-chronicles', testament: 'Old Testament', chapters: 36, verses: 822, summary: 'Second Chronicles covers the history of Judah from Solomon through the Babylonian exile, with emphasis on Temple worship.', themes: [{ name: 'Faithfulness', description: 'Faithful kings bring revival; unfaithful ones bring judgment.' }] },
    { name: 'Ezra', slug: 'ezra', testament: 'Old Testament', chapters: 10, verses: 280, summary: 'Ezra records the return from Babylonian exile and the rebuilding of the Temple under Zerubbabel and Ezra\'s reforms.', themes: [{ name: 'Restoration', description: 'God restores His people and their worship.' }] },
    { name: 'Nehemiah', slug: 'nehemiah', testament: 'Old Testament', chapters: 13, verses: 406, summary: 'Nehemiah tells of the rebuilding of Jerusalem\'s walls and the spiritual renewal of the returned exiles.', themes: [{ name: 'Leadership', description: 'Nehemiah models godly leadership in rebuilding.' }, { name: 'Revival', description: 'The people recommit to God\'s covenant.' }] },
    { name: 'Esther', slug: 'esther', testament: 'Old Testament', chapters: 10, verses: 167, summary: 'Esther tells how a Jewish queen saves her people from genocide in Persia, revealing God\'s hidden providence.', themes: [{ name: 'Providence', description: 'God works behind the scenes to protect His people.' }, { name: 'Courage', description: 'Esther risks her life for her people.' }] },
    { name: 'Job', slug: 'job', testament: 'Old Testament', chapters: 42, verses: 1070, summary: 'Job explores the mystery of suffering through the story of a righteous man who loses everything yet maintains his faith in God.', themes: [{ name: 'Suffering', description: 'Why do the righteous suffer?' }, { name: 'Sovereignty', description: 'God\'s wisdom transcends human understanding.' }] },
    { name: 'Psalms', slug: 'psalms', testament: 'Old Testament', chapters: 150, verses: 2461, author: 'David and others', summary: 'Psalms is a collection of 150 songs, prayers, and poems expressing the full range of human emotion — from praise to lament — directed toward God.\n\nIt serves as the prayer book and hymnal of ancient Israel and remains central to Christian worship.', themes: [{ name: 'Praise', description: 'Celebrating God\'s greatness, faithfulness, and love.' }, { name: 'Lament', description: 'Honest cries to God in times of suffering.' }, { name: 'Trust', description: 'Finding refuge and hope in God.' }] },
    { name: 'Proverbs', slug: 'proverbs', testament: 'Old Testament', chapters: 31, verses: 915, author: 'Solomon and others', summary: 'Proverbs is a collection of wise sayings covering practical topics from relationships to work ethics, all rooted in the fear of the Lord.', themes: [{ name: 'Wisdom', description: 'The fear of the Lord is the beginning of wisdom.' }, { name: 'Practical Living', description: 'Guidance for everyday decisions and relationships.' }] },
    { name: 'Ecclesiastes', slug: 'ecclesiastes', testament: 'Old Testament', chapters: 12, verses: 222, author: 'Solomon', summary: 'Ecclesiastes reflects on the meaning of life, concluding that apart from God, all human endeavors are ultimately meaningless.', themes: [{ name: 'Meaning', description: 'True meaning is found only in relationship with God.' }] },
    { name: 'Song of Solomon', slug: 'song-of-solomon', testament: 'Old Testament', chapters: 8, verses: 117, author: 'Solomon', summary: 'Song of Solomon is a love poem celebrating romantic love between a bride and groom, often interpreted as an allegory of God\'s love.', themes: [{ name: 'Love', description: 'The beauty and power of romantic love.' }] },
    { name: 'Isaiah', slug: 'isaiah', testament: 'Old Testament', chapters: 66, verses: 1292, author: 'Isaiah', summary: 'Isaiah proclaims both judgment and hope, containing some of the most profound messianic prophecies in the Bible.', themes: [{ name: 'Judgment', description: 'God judges sin but offers redemption.' }, { name: 'Messiah', description: 'Detailed prophecies of the coming Savior.' }, { name: 'Hope', description: 'God promises restoration and a new creation.' }] },
    { name: 'Jeremiah', slug: 'jeremiah', testament: 'Old Testament', chapters: 52, verses: 1364, author: 'Jeremiah', summary: 'Jeremiah, the "weeping prophet," warns Judah of coming judgment while promising a new covenant.', themes: [{ name: 'Warning', description: 'Persistent calls to repentance.' }, { name: 'New Covenant', description: 'God promises to write His law on hearts.' }] },
    { name: 'Lamentations', slug: 'lamentations', testament: 'Old Testament', chapters: 5, verses: 154, author: 'Jeremiah', summary: 'Lamentations mourns the destruction of Jerusalem, expressing deep grief while affirming God\'s faithfulness.', themes: [{ name: 'Grief', description: 'Honest mourning over devastating loss.' }, { name: 'Faithfulness', description: 'God\'s mercies are new every morning.' }] },
    { name: 'Ezekiel', slug: 'ezekiel', testament: 'Old Testament', chapters: 48, verses: 1273, author: 'Ezekiel', summary: 'Ezekiel contains powerful visions and prophecies from the exile, including the valley of dry bones and the future Temple.', themes: [{ name: 'God\'s Glory', description: 'God\'s glory departs and promises to return.' }, { name: 'Renewal', description: 'God promises spiritual resurrection for His people.' }] },
    { name: 'Daniel', slug: 'daniel', testament: 'Old Testament', chapters: 12, verses: 357, author: 'Daniel', summary: 'Daniel tells of faithful Jews in Babylonian exile and contains apocalyptic visions of future kingdoms and God\'s ultimate victory.', themes: [{ name: 'Faithfulness', description: 'Standing firm in faith despite persecution.' }, { name: 'Sovereignty', description: 'God rules over all earthly kingdoms.' }] },
    { name: 'Hosea', slug: 'hosea', testament: 'Old Testament', chapters: 14, verses: 197, summary: 'Hosea uses the prophet\'s marriage to an unfaithful wife as a metaphor for God\'s persistent love for unfaithful Israel.', themes: [{ name: 'Unfailing Love', description: 'God\'s love pursues His people despite their unfaithfulness.' }] },
    { name: 'Joel', slug: 'joel', testament: 'Old Testament', chapters: 3, verses: 73, summary: 'Joel calls for repentance in the face of a devastating locust plague and prophesies the outpouring of God\'s Spirit.', themes: [{ name: 'Repentance', description: 'A call to return to God with all your heart.' }] },
    { name: 'Amos', slug: 'amos', testament: 'Old Testament', chapters: 9, verses: 146, summary: 'Amos, a shepherd-prophet, pronounces God\'s judgment on Israel for social injustice and religious hypocrisy.', themes: [{ name: 'Justice', description: 'God demands justice for the poor and oppressed.' }] },
    { name: 'Obadiah', slug: 'obadiah', testament: 'Old Testament', chapters: 1, verses: 21, summary: 'Obadiah, the shortest Old Testament book, prophesies judgment against Edom for their arrogance and mistreatment of Israel.', themes: [{ name: 'Pride', description: 'God opposes the proud and arrogant.' }] },
    { name: 'Jonah', slug: 'jonah', testament: 'Old Testament', chapters: 4, verses: 48, summary: 'Jonah tells the story of a reluctant prophet who learns about God\'s compassion for all people, even Israel\'s enemies.', themes: [{ name: 'Compassion', description: 'God\'s mercy extends to all nations.' }, { name: 'Obedience', description: 'Running from God\'s call leads to trouble.' }] },
    { name: 'Micah', slug: 'micah', testament: 'Old Testament', chapters: 7, verses: 105, summary: 'Micah pronounces judgment on Israel and Judah while prophesying the Messiah\'s birth in Bethlehem.', themes: [{ name: 'Justice', description: 'God requires justice, mercy, and humility.' }] },
    { name: 'Nahum', slug: 'nahum', testament: 'Old Testament', chapters: 3, verses: 47, summary: 'Nahum prophesies the fall of Nineveh and Assyria, demonstrating God\'s justice against oppressive nations.', themes: [{ name: 'Justice', description: 'God will not leave the guilty unpunished.' }] },
    { name: 'Habakkuk', slug: 'habakkuk', testament: 'Old Testament', chapters: 3, verses: 56, summary: 'Habakkuk wrestles with God about injustice and learns to live by faith despite difficult circumstances.', themes: [{ name: 'Faith', description: 'The righteous shall live by faith.' }] },
    { name: 'Zephaniah', slug: 'zephaniah', testament: 'Old Testament', chapters: 3, verses: 53, summary: 'Zephaniah warns of the coming Day of the Lord but promises restoration for a humble remnant.', themes: [{ name: 'Day of the Lord', description: 'God\'s coming judgment and subsequent restoration.' }] },
    { name: 'Haggai', slug: 'haggai', testament: 'Old Testament', chapters: 2, verses: 38, summary: 'Haggai urges the returned exiles to rebuild the Temple and prioritize God\'s house above personal comfort.', themes: [{ name: 'Priorities', description: 'Put God first in your life and efforts.' }] },
    { name: 'Zechariah', slug: 'zechariah', testament: 'Old Testament', chapters: 14, verses: 211, summary: 'Zechariah contains messianic prophecies and apocalyptic visions, encouraging the rebuilding of the Temple.', themes: [{ name: 'Messiah', description: 'Prophecies of the coming King who will be pierced.' }] },
    { name: 'Malachi', slug: 'malachi', testament: 'Old Testament', chapters: 4, verses: 55, summary: 'Malachi, the last Old Testament prophet, confronts Israel\'s spiritual apathy and promises the coming messenger.', themes: [{ name: 'Faithfulness', description: 'God calls His people back to wholehearted devotion.' }] },
    { name: 'Matthew', slug: 'matthew', testament: 'New Testament', chapters: 28, verses: 1071, author: 'Matthew', summary: 'Matthew presents Jesus as the promised Messiah and King of the Jews, featuring His teachings, miracles, death, and resurrection.\n\nIt includes the Sermon on the Mount, the Great Commission, and extensive Old Testament fulfillment quotations.', themes: [{ name: 'Kingdom', description: 'Jesus inaugurates the Kingdom of Heaven.' }, { name: 'Fulfillment', description: 'Jesus fulfills Old Testament prophecy.' }, { name: 'Discipleship', description: 'Following Jesus requires total commitment.' }] },
    { name: 'Mark', slug: 'mark', testament: 'New Testament', chapters: 16, verses: 678, author: 'John Mark', summary: 'Mark is the shortest Gospel, presenting Jesus as the suffering servant who acts with authority and power.', themes: [{ name: 'Servanthood', description: 'Jesus came to serve, not to be served.' }, { name: 'Action', description: 'Mark emphasizes what Jesus did, moving quickly between events.' }] },
    { name: 'Luke', slug: 'luke', testament: 'New Testament', chapters: 24, verses: 1151, author: 'Luke', summary: 'Luke provides a detailed, orderly account of Jesus\' life, emphasizing His compassion for outcasts, women, and the poor.', themes: [{ name: 'Compassion', description: 'Jesus seeks and saves the lost.' }, { name: 'Joy', description: 'The good news of Jesus brings great joy to all people.' }] },
    { name: 'John', slug: 'john', testament: 'New Testament', chapters: 21, verses: 879, author: 'John', summary: 'John presents Jesus as the divine Son of God through seven miraculous signs and seven "I Am" statements.\n\nIt is the most theological of the four Gospels, written so that readers may believe and have life in Jesus\' name.', themes: [{ name: 'Belief', description: 'The central call to believe in Jesus for eternal life.' }, { name: 'Light', description: 'Jesus is the light of the world who overcomes darkness.' }, { name: 'Life', description: 'Jesus offers abundant and eternal life.' }] },
    { name: 'Acts', slug: 'acts', testament: 'New Testament', chapters: 28, verses: 1007, author: 'Luke', summary: 'Acts records the birth and growth of the early church through the power of the Holy Spirit, from Jerusalem to Rome.', themes: [{ name: 'Holy Spirit', description: 'The Spirit empowers the church for mission.' }, { name: 'Mission', description: 'The gospel spreads from Jerusalem to the ends of the earth.' }] },
    { name: 'Romans', slug: 'romans', testament: 'New Testament', chapters: 16, verses: 433, author: 'Paul', summary: 'Romans is Paul\'s masterpiece of theology, systematically explaining salvation by grace through faith, justification, and the Christian life.', themes: [{ name: 'Justification', description: 'We are made right with God through faith, not works.' }, { name: 'Grace', description: 'God\'s unmerited favor transforms lives.' }] },
    { name: '1 Corinthians', slug: '1-corinthians', testament: 'New Testament', chapters: 16, verses: 437, author: 'Paul', summary: 'First Corinthians addresses divisions, moral issues, and doctrinal questions in the church at Corinth, including the famous "love chapter."', themes: [{ name: 'Unity', description: 'The church is one body with many parts.' }, { name: 'Love', description: 'Love is the greatest of all spiritual gifts.' }] },
    { name: '2 Corinthians', slug: '2-corinthians', testament: 'New Testament', chapters: 13, verses: 257, author: 'Paul', summary: 'Second Corinthians reveals Paul\'s heart, defending his ministry and teaching about strength in weakness.', themes: [{ name: 'Strength in Weakness', description: 'God\'s power is made perfect in weakness.' }] },
    { name: 'Galatians', slug: 'galatians', testament: 'New Testament', chapters: 6, verses: 149, author: 'Paul', summary: 'Galatians passionately defends the gospel of grace against legalism, declaring freedom in Christ.', themes: [{ name: 'Freedom', description: 'Christ has set us free from the law.' }, { name: 'Grace', description: 'Salvation is by grace through faith alone.' }] },
    { name: 'Ephesians', slug: 'ephesians', testament: 'New Testament', chapters: 6, verses: 155, author: 'Paul', summary: 'Ephesians explores the riches of God\'s grace, the unity of the church, and practical Christian living.', themes: [{ name: 'Grace', description: 'Saved by grace through faith.' }, { name: 'Unity', description: 'Jew and Gentile are one in Christ.' }] },
    { name: 'Philippians', slug: 'philippians', testament: 'New Testament', chapters: 4, verses: 104, author: 'Paul', summary: 'Philippians is Paul\'s letter of joy from prison, encouraging believers to rejoice in all circumstances.', themes: [{ name: 'Joy', description: 'Rejoice in the Lord always.' }, { name: 'Contentment', description: 'Finding contentment in Christ alone.' }] },
    { name: 'Colossians', slug: 'colossians', testament: 'New Testament', chapters: 4, verses: 95, author: 'Paul', summary: 'Colossians proclaims the supremacy of Christ over all creation and warns against false teachings.', themes: [{ name: 'Supremacy of Christ', description: 'Christ is before all things and holds all things together.' }] },
    { name: '1 Thessalonians', slug: '1-thessalonians', testament: 'New Testament', chapters: 5, verses: 89, author: 'Paul', summary: 'First Thessalonians encourages a young church and teaches about the return of Christ.', themes: [{ name: 'Hope', description: 'The hope of Christ\'s return.' }] },
    { name: '2 Thessalonians', slug: '2-thessalonians', testament: 'New Testament', chapters: 3, verses: 47, author: 'Paul', summary: 'Second Thessalonians clarifies end-times teaching and encourages perseverance in faith.', themes: [{ name: 'Perseverance', description: 'Stand firm and hold to the teachings.' }] },
    { name: '1 Timothy', slug: '1-timothy', testament: 'New Testament', chapters: 6, verses: 113, author: 'Paul', summary: 'First Timothy provides pastoral guidance on church leadership, sound doctrine, and godly living.', themes: [{ name: 'Leadership', description: 'Qualifications and responsibilities of church leaders.' }] },
    { name: '2 Timothy', slug: '2-timothy', testament: 'New Testament', chapters: 4, verses: 83, author: 'Paul', summary: 'Second Timothy is Paul\'s final letter, urging Timothy to guard the gospel and endure hardship.', themes: [{ name: 'Endurance', description: 'Endure hardship as a good soldier of Christ.' }] },
    { name: 'Titus', slug: 'titus', testament: 'New Testament', chapters: 3, verses: 46, author: 'Paul', summary: 'Titus instructs a young pastor on establishing church order and promoting good works on the island of Crete.', themes: [{ name: 'Good Works', description: 'Grace motivates believers to do good.' }] },
    { name: 'Philemon', slug: 'philemon', testament: 'New Testament', chapters: 1, verses: 25, author: 'Paul', summary: 'Philemon is a personal letter asking a slave owner to receive back his runaway slave Onesimus as a brother in Christ.', themes: [{ name: 'Reconciliation', description: 'The gospel transforms relationships.' }] },
    { name: 'Hebrews', slug: 'hebrews', testament: 'New Testament', chapters: 13, verses: 303, summary: 'Hebrews demonstrates Christ\'s superiority over angels, Moses, and the old covenant, including the famous "Hall of Faith" in chapter 11.', themes: [{ name: 'Superiority of Christ', description: 'Jesus is greater than all that came before.' }, { name: 'Faith', description: 'The heroes of faith inspire endurance.' }] },
    { name: 'James', slug: 'james', testament: 'New Testament', chapters: 5, verses: 108, author: 'James', summary: 'James is a practical letter emphasizing that genuine faith produces good works, addressing topics like trials, wisdom, and taming the tongue.', themes: [{ name: 'Faith and Works', description: 'Faith without works is dead.' }, { name: 'Practical Wisdom', description: 'Wisdom from above is pure, peaceable, and gentle.' }] },
    { name: '1 Peter', slug: '1-peter', testament: 'New Testament', chapters: 5, verses: 105, author: 'Peter', summary: 'First Peter encourages suffering Christians to stand firm in grace and live holy lives as strangers in this world.', themes: [{ name: 'Suffering', description: 'Rejoice in trials that refine your faith.' }, { name: 'Hope', description: 'A living hope through the resurrection of Christ.' }] },
    { name: '2 Peter', slug: '2-peter', testament: 'New Testament', chapters: 3, verses: 61, author: 'Peter', summary: 'Second Peter warns against false teachers and encourages growth in the knowledge of Christ.', themes: [{ name: 'Growth', description: 'Grow in the grace and knowledge of our Lord.' }] },
    { name: '1 John', slug: '1-john', testament: 'New Testament', chapters: 5, verses: 105, author: 'John', summary: 'First John explores the themes of love, light, and assurance, helping believers know they have eternal life.', themes: [{ name: 'Love', description: 'God is love, and we are called to love one another.' }, { name: 'Assurance', description: 'You can know that you have eternal life.' }] },
    { name: '2 John', slug: '2-john', testament: 'New Testament', chapters: 1, verses: 13, author: 'John', summary: 'Second John warns against false teachers and encourages walking in truth and love.', themes: [{ name: 'Truth', description: 'Walk in truth and beware of deceivers.' }] },
    { name: '3 John', slug: '3-john', testament: 'New Testament', chapters: 1, verses: 15, author: 'John', summary: 'Third John commends Gaius for his hospitality and warns against Diotrephes\' arrogance.', themes: [{ name: 'Hospitality', description: 'Support those who work for the truth.' }] },
    { name: 'Jude', slug: 'jude', testament: 'New Testament', chapters: 1, verses: 25, author: 'Jude', summary: 'Jude urgently warns against false teachers and calls believers to contend earnestly for the faith.', themes: [{ name: 'Contending for Faith', description: 'Fight for sound doctrine against false teaching.' }] },
    { name: 'Revelation', slug: 'revelation', testament: 'New Testament', chapters: 22, verses: 404, author: 'John', summary: 'Revelation is an apocalyptic vision of the end times, depicting the ultimate triumph of God over evil and the establishment of a new heaven and new earth.\n\nIt offers hope to persecuted believers that God\'s justice will prevail and Christ will return in glory.', themes: [{ name: 'Victory', description: 'God and His people triumph over evil.' }, { name: 'Worship', description: 'Heaven resounds with praise to the Lamb.' }, { name: 'New Creation', description: 'God makes all things new.' }] },
];

function findKeyVerses(bookName: string, limit = 5) {
    const allVerses = priorityVerses as PriorityVerse[];
    const bookVerses = allVerses.filter(v => v.book === bookName);
    // Take evenly spaced verses from the book for variety
    if (bookVerses.length <= limit) return bookVerses;
    const step = Math.floor(bookVerses.length / limit);
    const selected: PriorityVerse[] = [];
    for (let i = 0; i < limit && i * step < bookVerses.length; i++) {
        selected.push(bookVerses[i * step]);
    }
    return selected;
}

export function getAllBookSlugs(): string[] {
    return BOOKS.map(b => b.slug);
}

export function getBookData(slug: string): BookPageData | null {
    const book = BOOKS.find(b => b.slug === slug);
    if (!book) return null;

    const keyVerses = findKeyVerses(book.name).map(v => ({
        chapter: v.chapter,
        verse: v.verse,
        slug: v.slug,
        text: v.text_niv,
    }));

    return {
        name: book.name,
        slug: book.slug,
        testament: book.testament,
        chapterCount: book.chapters,
        verseCount: book.verses,
        author: book.author,
        dateWritten: book.dateWritten,
        summary: book.summary,
        themes: book.themes,
        keyVerses,
    };
}

/**
 * Get adjacent (prev/next) books for navigation.
 */
export function getAdjacentBooks(slug: string): { prev: { name: string; slug: string } | null; next: { name: string; slug: string } | null } {
    const index = BOOKS.findIndex(b => b.slug === slug);
    if (index === -1) return { prev: null, next: null };

    return {
        prev: index > 0 ? { name: BOOKS[index - 1].name, slug: BOOKS[index - 1].slug } : null,
        next: index < BOOKS.length - 1 ? { name: BOOKS[index + 1].name, slug: BOOKS[index + 1].slug } : null,
    };
}
