/**
 * Save Generated Content to Database
 * Content generated by Claude agent directly
 */

const { Pool } = require('pg');
const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '../.env.local') });

const pool = new Pool({
  connectionString: process.env.DATABASE_URL
});

async function saveContent(slug, content) {
  try {
    // Update main content
    await pool.query(`
      UPDATE verses
      SET 
        context = $1,
        meaning = $2,
        application = $3,
        prayer = $4,
        updated_at = NOW()
      WHERE slug = $5
    `, [
      content.context,
      content.meaning,
      content.application,
      content.prayer,
      slug
    ]);
    
    // Save FAQs
    for (const faq of content.faqs) {
      await pool.query(`
        INSERT INTO faqs (page_type, page_id, question, answer)
        SELECT 'verse', id, $1, $2
        FROM verses
        WHERE slug = $3
        ON CONFLICT (page_type, page_id, question) DO UPDATE
        SET answer = EXCLUDED.answer
      `, [faq.question, faq.answer, slug]);
    }
    
    console.log(`✅ ${slug}`);
    return true;
    
  } catch (error) {
    console.error(`❌ ${slug}:`, error.message);
    return false;
  }
}

// CONTENT DATA - Generated by Claude Agent
const VERSE_CONTENT = {
  'john-3-16': {
    context: "John 3:16 appears in the Gospel of John, written by the Apostle John between 85-90 AD. This verse is part of Jesus's nighttime conversation with Nicodemus, a Pharisee and member of the Jewish ruling council. The setting is crucial: Nicodemus came to Jesus under cover of darkness, seeking answers about this rabbi who performed miraculous signs. Jesus had just explained the concept of being \"born again\" to the confused religious leader. This conversation, found in John chapter 3, represents one of the most theologically rich dialogues in Scripture. The verse itself is often called \"the gospel in a nutshell\" because it encapsulates the entire Christian message of salvation. John's Gospel, unlike the synoptic gospels, focuses heavily on Jesus's divinity and his role as the Son of God. This particular verse uses the Greek word \"agape\" for love, indicating God's unconditional, sacrificial love for humanity. The historical context shows a world under Roman occupation, where many Jews expected a political messiah. Instead, Jesus reveals a spiritual salvation available to all people.",
    
    meaning: "The profound depth of John 3:16 reveals the core of Christian theology. \"For God so loved the world\" begins with the motivation behind salvation - not human merit or works, but divine love. The Greek construction emphasizes the magnitude: God loved \"in this manner\" or \"to this extent.\" The word \"world\" (kosmos) refers not just to the planet but to all humanity in rebellion against God. This universal scope was revolutionary, as many Jews believed God's favor was exclusively for Israel. \"That he gave his only begotten Son\" speaks to the costliness of salvation. The term \"only begotten\" (monogenes) means unique, one-of-a-kind. God didn't send a prophet or angel, but gave His own Son - the ultimate sacrifice. This gift wasn't forced; it was voluntary, motivated by love. \"That whosoever believeth in him\" establishes the condition: faith. Not works, heritage, or ritual observance, but simple trust in Jesus Christ. The Greek word for \"believe\" (pisteuo) means more than intellectual assent; it implies complete trust and reliance. \"Should not perish, but have everlasting life\" presents two eternal destinies. \"Perish\" (apollumi) means to be destroyed or ruined, referring to eternal separation from God. Conversely, \"everlasting life\" (aionios zoe) describes not merely endless existence but quality of life - intimate relationship with God beginning now and continuing forever. This verse encapsulates substitutionary atonement, unconditional love, universal offer, and eternal consequences.",
    
    application: "Understanding John 3:16 transforms how we live daily. First, recognizing God's love for us personally changes our self-perception. Many struggle with feelings of worthlessness or inadequacy. This verse declares that you are so valuable that God gave His most precious treasure for you. When facing rejection, failure, or despair, remember: you matter to the Creator of the universe. Second, this verse should inspire gratitude and worship. Consider starting each day reflecting on God's gift - it cost Him everything, yet He offers it freely. This awareness naturally leads to a heart of thanksgiving rather than entitlement. Third, the universal scope of \"whosoever\" eliminates barriers we erect. Have you written off certain people as \"too far gone\" for God's grace? John 3:16 reminds us that salvation is available to anyone who believes. This should fuel evangelism and compassion for those different from us. Fourth, the simplicity of \"believe\" removes religious complexity. You don't need to achieve a certain spiritual level or complete rituals. Faith in Jesus is sufficient. If you're struggling with assurance of salvation, rest in this promise: belief equals eternal life. Finally, the reality of \"perish\" should motivate us to share this message urgently. People we love face an eternity without God unless they trust in Christ. This isn't about fear-mongering but about genuine love - if you knew someone's house was on fire, wouldn't you warn them? Share this verse with someone this week who needs hope.",
    
    prayer: "Heavenly Father, I stand amazed at the depth of Your love demonstrated in John 3:16. Thank You for loving me when I was unlovable, for giving Your Son when I deserved judgment. Jesus, thank You for willingly laying down Your life for me. Help me to never take this gift for granted or reduce it to mere words on a page. I believe in You, Lord - not just as historical fact, but as my personal Savior and Lord. Strengthen my faith when doubts arise. Fill me with gratitude that overflows into worship and service. Help me to see others through Your eyes - as people You love enough to die for. Give me boldness to share this good news with those who need it. May the reality of eternal life transform how I live today, making choices that honor Your sacrifice. In Jesus's precious name, Amen.",
    
    faqs: [
      {
        question: "What does 'only begotten Son' mean?",
        answer: "The phrase 'only begotten Son' translates the Greek word 'monogenes,' which literally means 'one of a kind' or 'unique.' It emphasizes Jesus's special relationship with God the Father - not that He was created (as some misinterpret) but that He is the unique Son of God, sharing the divine nature in a way no one else does. While Christians are called children of God through adoption, Jesus is the Son of God by eternal nature. This distinction is crucial: Jesus isn't one of many sons, but the one-and-only Son who has existed eternally with the Father. Some modern translations use 'one and only Son' to capture this meaning more clearly. The term underscores the magnitude of God's gift - He didn't send just any messenger, but His most precious, irreplaceable Son. This uniqueness also validates Jesus's claims about Himself and His authority to offer salvation. Understanding this helps us appreciate the cost of our redemption and the privilege of being adopted into God's family through faith in His unique Son."
      },
      {
        question: "Does God really love the whole world, including sinners?",
        answer: "Absolutely yes - this is perhaps the most revolutionary aspect of John 3:16. The word 'world' (kosmos in Greek) refers to all humanity, regardless of ethnicity, social status, or moral condition. In the Jewish context, this was shocking because many believed God's love was reserved for Israel. But Jesus explicitly states God's love extends to everyone. This includes people living in active rebellion against God - not because He approves of sin, but because He desires their redemption. Romans 5:8 confirms this: 'While we were still sinners, Christ died for us.' God's love isn't reactive (based on our goodness) but proactive (based on His nature). However, loving the whole world doesn't mean everyone will be saved - the condition is faith ('whosoever believes'). God's love is universal in its offer but requires a response. Think of it like a lifeline thrown to a drowning person - the lifeline is offered to everyone, but only those who grab it are saved. This should give us hope about people we think are 'too far gone' and motivate us to share the gospel widely, knowing no one is beyond God's reach."
      },
      {
        question: "What exactly does it mean to 'believe' in Jesus?",
        answer: "Biblical belief goes far deeper than intellectual acknowledgment. James 2:19 notes that even demons 'believe' God exists and tremble - but they aren't saved. The Greek word 'pisteuo' used in John 3:16 means to trust in, rely upon, and commit to. It's like the difference between believing a chair exists and actually sitting in it, trusting it to hold your weight. True belief in Jesus means trusting Him alone for salvation, not your good works or religious activities. It involves three components: intellectual (understanding who Jesus is and what He did), emotional (being moved by this truth), and volitional (choosing to commit your life to Him). It's surrendering control and saying, 'Jesus, I trust You as my Lord and Savior.' This belief isn't a one-time mental exercise but an ongoing relationship of trust. When you truly believe, it changes how you live - not to earn salvation, but because you've been transformed. If your 'belief' hasn't affected your life, examine whether it's genuine faith or mere intellectual assent. True saving faith produces fruit, though the fruit doesn't save you - faith alone does."
      },
      {
        question: "Can someone lose their salvation according to this verse?",
        answer: "This is a debated question among Christians, but John 3:16 itself emphasizes the security provided by genuine faith. The promise is clear: those who believe 'have' (present tense) everlasting life - not 'might have' or 'will have if they maintain it.' Everlasting means exactly that - eternal, without end. If it could end, it wouldn't be everlasting. Other Scriptures support this security: John 10:28-29 says no one can snatch believers from Jesus's or the Father's hand; Romans 8:38-39 declares nothing can separate us from God's love; Ephesians 1:13-14 describes believers as sealed by the Holy Spirit as a guarantee. However, this security doesn't mean Christians can live however they want - genuine faith produces transformation and perseverance. First John 2:19 suggests those who permanently abandon faith may never have truly believed in the first place. The key is distinguishing between temporary struggles or doubts (which all believers face) and complete, final rejection of Christ. True believers may stumble, but they don't completely and permanently fall away. This isn't a license for careless living but a comfort for those who genuinely trust Christ yet struggle with assurance. The question isn't whether you've been perfect, but whether your faith in Jesus remains."
      }
    ]
  }
};

async function main() {
  console.log('🚀 Saving Generated Content\n');
  
  let count = 0;
  for (const [slug, content] of Object.entries(VERSE_CONTENT)) {
    const success = await saveContent(slug, content);
    if (success) count++;
  }
  
  console.log(`\n✅ Saved ${count}/${Object.keys(VERSE_CONTENT).length} verses\n`);
  await pool.end();
}

main();
